name: Display Workflow
on: push

jobs:
  show-name-of-folder:
    runs-on: ubuntu-latest
    steps:
      - name: List files before
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
      - name: Lisst files after
        run: ls -a
