name: First Workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline commend
        run: |
          node -v
          npm -v
  parallel-job:
    runs-on: macos-latest
    steps:
      - name: View SW version
        run: sw_vers
  dependend-job:
    runs-on: windows-latest
    needs: run-shell-commands
    steps:
      - name: Display strings
        run: Write-Output "Hello World from Windows"
      - name: Display error
        run: runsomething
