name: runs-on-pull-requests
on: [pull_request]
jobs:
  display-the-name:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-test
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
      - uses: actions/checkout@v3
