name: runs-on-pull-requests
on:
  pull_request:
    types: [opened, reopened]

jobs:
  checkout-test:
    runs-on: ubuntu-latest
    steps:
      - name: test the refs
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
      - uses: actions/checkout@v3
